### ISSUE TITLE
the pth is not a fie but a folder,how to solve?

### ISSUE THREAD

**Issue by Lin-yi-er** [Reagan1311/LOCATE#6]
when I downloaded the model file in the onedrive, I found it's a folder but not a file, so when I use it  and try to run test,it is wrong.
 Traceback (most recent call last):
  File "test.py", line 76, in <module>
    model.load_state_dict(torch.load(args.model_file))
  File "/home/linyi/anaconda3/envs/afford/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/linyi/anaconda3/envs/afford/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/linyi/anaconda3/envs/afford/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/home/linyi/Code/LOCATE/best_seen.pth'

**Comment by Reagan1311** [comment]
Hi, I tried loading the model file again, and it worked well on my end. Maybe you could try redownloading the file to see if that resolves the issue.

**Comment by Lin-yi-er** [comment]
OK, thank you! I have solved the problem. Thanks again!
